//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryView
    {
        public int TagId { get; set; }
        public string TagFriendlyName { get; set; }
        public Nullable<System.DateTime> Reading { get; set; }
        public string Location { get; set; }
    }
}
